name: Deploy my protfolio application on dev server

on:
  push:
    branches:
      - v1.x

jobs:
  self-hosted-build:
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/iamalamin/protfolio
            git pull origin v1.x
            
  build-on-github-server:
    runs-on: ubuntu-latest
    needs: self-hosted-build
    if: ${{ needs.self-hosted-build.result != 'success' }}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/iamalamin/protfolio
            git pull origin v1.x
