name: Deploy my protfolio application on dev server

on:
  push:
    branches:
      - v1.x

jobs:
  build:
    name: Build in dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v2
          with:
            node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
      # - name: Use Node.js v16.14.2
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: v16.14.2
      #     script: |
      #       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
      #       curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      #       source ~/.bashrc
      #       nvm list-remote
      #       nvm install v16.14.2
      #       nvm install lts/fermium
      #       echo node -v
      #       npm install
      #       npm run build

  deploy:
    needs: build
    name: Dev deployment process
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/iamalamin/protfolio
            git pull origin v1.x
