name: Deploy my protfolio application on production server

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on production dd
        shell: bash
        run: |
          echo "Successfully deploy on production"
