name: Deploy my protfolio application on Staging Server

on:
  push:
    tags:
      - "v*.*.*-RC.*"

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging
        shell: bash
        run: |
          echo "Successfully deploy on staging"
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.action }}
          echo "branch: " ${{github.ref}}
          echo "branch name: " ${{github.ref_name}}
