name: Deploy my protfolio application on Staging Server

on:
  push:
    tags:
      - "v[0-100]+.[0-100]+.[0-100]+-RC.[0-100]"

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging
        shell: bash
        run: |
          echo "Successfully deploy on staging"
