name: Deploy my protfolio application on Staging Server

on:
  push:
    tags:
      - "v\d+.\d+.\d+-RC.\d"

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging
        shell: bash
        run: |
          echo "Successfully deploy on staging"
