name: Deploy my protfolio application on Staging Server

on:
  push:
    tags:
      - "v[0-9]+.[0-9]*+.[0-9]*+-RC.[0-9]*"

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on staging
        shell: bash
        run: |
          echo "Successfully deploy on staging"
          steps:
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.action }}
